all: prolific generation explorer slug slugrace

prolific: prolific.c
	gcc -Wall prolific.c -o prolific

generation: generation.c
	gcc -Wall generation.c -o generation

explorer: explorer.c
	gcc -Wall explorer.c -o explorer

slug: slug.c
	gcc -Wall slug.c -o slug

slugrace: slugrace.c
	gcc -Wall slugrace.c -o slugrace

clean:
	rm prolific generation explorer slug slugrace
